# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 258d95f2fcdbdd7ff4754c22cf9b81c0afb6c34dfe785aa5312b8c693cbb56b63df5f7f47367ab1220922701a6151c1c5ce4b0515f1ec3055c0ab5a56e7f7fa5

test:
  secret_key_base: b114a3fd061fcdb0826fca54af4b8576b24c932f6a29e79bbef600428f4624fadebdb259a85e6a9e270f6b895a22d6dfa548483c8d5a10d5879867fd198c5a7b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
